config/routes.rb
Rails.application.routes.draw do
  root 'main#index'

  get '/reports', to: 'reports#index'
  get '/reports/report_by_category', to: 'reports#report_by_category'
  get '/reports/report_by_dates', to: 'reports#report_by_dates'

  resources :operations
  resources :categories
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :operations

  validates :name, :description, presence: true # validates_presence_of :name, :description

  validates :name, uniqueness: true

  # Paginator [https://github.com/kaminari/kaminari]
  paginates_per 30 # default

  # search for categories by name
  scope :search_by_category_name_scope, ->(name) { Category.where('LOWER(name) LIKE ?', "%#{name.gsub('+', ' ').downcase}%").order(:name) }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @pageTitle = 'Your categories'

    # array of category names for jQuery search field
    @array_of_category_names = Category.pluck(:name)

    nameSort = params[:nameSort]
    idSort = params[:idSort]

    category_name = params[:search_by_category_name]

    if category_name != '' && !category_name.nil?
      return @categories = Category.search_by_category_name_scope(category_name).page(params[:page])
    end

    return @categories = Category.all.order(:name).page(params[:page]) if nameSort == 'Alphabetically'

    return @categories = Category.all.order(name: :desc).page(params[:page]) if nameSort == 'AlphabeticallyReversed'

    return @categories = Category.all.order(:id).page(params[:page]) if idSort == 'Ascending'

    return @categories = Category.all.order(id: :desc).page(params[:page]) if idSort == 'Descending'

    # by Default ordered by name Alphabetically
    @categories = Category.all.order(:name).page(params[:page])
  end

  # GET /categories/1 or /categories/1.json
  def show
    @pageTitle = "Category #{@category.id}"
  end

  # GET /categories/new
  def new
    @pageTitle = 'New category'

    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
    @pageTitle = "Edit category #{@category.id}"
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    # If the user decides to delete a category, then all operations that belong to this category will also be deleted.
    Operation.delete(Operation.where(category_id: @category.id).ids)
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :description)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <tr class="bg-white border-b dark:bg-gray-900 dark:border-gray-700">
    <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
      <%= category.id %>
    </th>
    <td class="px-6 py-4">
      <%= link_to category.name, category, class: "text-lg text-blue-500" %>
    </td>
    <td class="px-6 py-4">
      <%= category.description %>
    </td>
    <td class="px-6 py-4">
      <% if action_name != "show" %>
        <div class="flex justify-end">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-8 h-8">
            <a xlink:href="<%= "/categories/#{category.id}/edit" %>">
              <path d="M21.731 2.269a2.625 2.625 0 00-3.712 0l-1.157 1.157 3.712 3.712 1.157-1.157a2.625 2.625 0 000-3.712zM19.513 8.199l-3.712-3.712-8.4 8.4a5.25 5.25 0 00-1.32 2.214l-.8 2.685a.75.75 0 00.933.933l2.685-.8a5.25 5.25 0 002.214-1.32l8.4-8.4z" />
              <path d="M5.25 5.25a3 3 0 00-3 3v10.5a3 3 0 003 3h10.5a3 3 0 003-3V13.5a.75.75 0 00-1.5 0v5.25a1.5 1.5 0 01-1.5 1.5H5.25a1.5 1.5 0 01-1.5-1.5V8.25a1.5 1.5 0 011.5-1.5h5.25a.75.75 0 000-1.5H5.25z" />
            </a>
          </svg>
        </div>
      <% end %>
    </td>
  </tr>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category, class: "contents") do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, required: true, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_field :description, required: true, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing category</h1>

  <%= render "form", category: @category %>

  <%= link_to "Show this category", @category, class: "ml-2 rounded-lg py-3 px-5 bg-gray-300 inline-block font-medium mr-2" %>
  <%= link_to "Back to categories", categories_path, class: "rounded-lg mt-2 py-3 px-5 bg-gray-300 inline-block font-medium" %>
</div>

app/views/categories/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl my-5">Categories</h1>
    <%= link_to 'New category', new_category_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <%= form_tag "/categories", method: :get do %>
    <div class="flex items-center">
      <%= text_field_tag(:search_by_category_name, params[:search_by_category_name], id: "search_categories_by_name", class: "w-full block h-12 z-20 text-sm text-gray-900 bg-gray-50 border-gray-300", placeholder: "Category name...") %>
      <%= submit_tag "Search", class: "rounded-r-lg p-3 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
    </div>
    <a class="p-1 bg-red-600 text-white px-3 inline-block text-sm cursor-pointer rounded-b-lg" href="/categories">Reset</a>
    <b><%= @categories.total_count %></b> record(s)
  <% end %>

  <% if @categories.total_count != 0 %>

    <div class="my-2 text-center z-10 px-3 py-2 leading-tight dark:border-gray-700">
      <%= paginate @categories %>
    </div>

    <div id="categories" class="min-w-full">

      <div class="relative overflow-x-auto shadow-md sm:rounded-lg mb-5">
        <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
          <thead class="text-xs text-gray-700 uppercase bg-gray-300 dark:bg-gray-700 dark:text-gray-400">
          <tr>
            <th scope="col" class="px-6 py-3">
              <div class="flex items-center">
              ID

                <!--Sort Categories by id Ascending or Descending-->
                <% if request[:idSort] != 'Ascending' && request[:idSort] != 'Descending' %>
                  <a href="/categories?idSort=Descending"><svg xmlns="http://www.w3.org/2000/svg" class="w-3 h-3 ml-1" aria-hidden="true" fill="currentColor" viewBox="0 0 320 512"><path d="M27.66 224h264.7c24.6 0 36.89-29.78 19.54-47.12l-132.3-136.8c-5.406-5.406-12.47-8.107-19.53-8.107c-7.055 0-14.09 2.701-19.45 8.107L8.119 176.9C-9.229 194.2 3.055 224 27.66 224zM292.3 288H27.66c-24.6 0-36.89 29.77-19.54 47.12l132.5 136.8C145.9 477.3 152.1 480 160 480c7.053 0 14.12-2.703 19.53-8.109l132.3-136.8C329.2 317.8 316.9 288 292.3 288z"/></svg></a>
                <% else %>
                  <% if request[:idSort] == 'Descending' %>
                    <a href="/categories?idSort=Ascending"><svg xmlns="http://www.w3.org/2000/svg" class="w-3 h-3 ml-1" aria-hidden="true" fill="currentColor" viewBox="0 0 320 512"><path d="M27.66 224h264.7c24.6 0 36.89-29.78 19.54-47.12l-132.3-136.8c-5.406-5.406-12.47-8.107-19.53-8.107c-7.055 0-14.09 2.701-19.45 8.107L8.119 176.9C-9.229 194.2 3.055 224 27.66 224zM292.3 288H27.66c-24.6 0-36.89 29.77-19.54 47.12l132.5 136.8C145.9 477.3 152.1 480 160 480c7.053 0 14.12-2.703 19.53-8.109l132.3-136.8C329.2 317.8 316.9 288 292.3 288z"/></svg></a>
                  <% else %>
                    <a href="/categories?idSort=Descending"><svg xmlns="http://www.w3.org/2000/svg" class="w-3 h-3 ml-1" aria-hidden="true" fill="currentColor" viewBox="0 0 320 512"><path d="M27.66 224h264.7c24.6 0 36.89-29.78 19.54-47.12l-132.3-136.8c-5.406-5.406-12.47-8.107-19.53-8.107c-7.055 0-14.09 2.701-19.45 8.107L8.119 176.9C-9.229 194.2 3.055 224 27.66 224zM292.3 288H27.66c-24.6 0-36.89 29.77-19.54 47.12l132.5 136.8C145.9 477.3 152.1 480 160 480c7.053 0 14.12-2.703 19.53-8.109l132.3-136.8C329.2 317.8 316.9 288 292.3 288z"/></svg></a>
                  <% end %>
                <% end %>
              </div>
            </th>
            <th scope="col" class="px-6 py-3">
              <div class="flex items-center">
                Name

                <!--Sort Categories by name Alphabetically or AlphabeticallyReversed-->
                <% if request[:nameSort] != 'AlphabeticallyReversed' && request[:nameSort] != 'Alphabetically' %>
                  <a href="/categories?nameSort=AlphabeticallyReversed"><svg xmlns="http://www.w3.org/2000/svg" class="w-3 h-3 ml-1" aria-hidden="true" fill="currentColor" viewBox="0 0 320 512"><path d="M27.66 224h264.7c24.6 0 36.89-29.78 19.54-47.12l-132.3-136.8c-5.406-5.406-12.47-8.107-19.53-8.107c-7.055 0-14.09 2.701-19.45 8.107L8.119 176.9C-9.229 194.2 3.055 224 27.66 224zM292.3 288H27.66c-24.6 0-36.89 29.77-19.54 47.12l132.5 136.8C145.9 477.3 152.1 480 160 480c7.053 0 14.12-2.703 19.53-8.109l132.3-136.8C329.2 317.8 316.9 288 292.3 288z"/></svg></a>
                <% else %>
                  <% if request[:nameSort] == 'AlphabeticallyReversed' %>
                    <a href="/categories?nameSort=Alphabetically"><svg xmlns="http://www.w3.org/2000/svg" class="w-3 h-3 ml-1" aria-hidden="true" fill="currentColor" viewBox="0 0 320 512"><path d="M27.66 224h264.7c24.6 0 36.89-29.78 19.54-47.12l-132.3-136.8c-5.406-5.406-12.47-8.107-19.53-8.107c-7.055 0-14.09 2.701-19.45 8.107L8.119 176.9C-9.229 194.2 3.055 224 27.66 224zM292.3 288H27.66c-24.6 0-36.89 29.77-19.54 47.12l132.5 136.8C145.9 477.3 152.1 480 160 480c7.053 0 14.12-2.703 19.53-8.109l132.3-136.8C329.2 317.8 316.9 288 292.3 288z"/></svg></a>
                  <% else %>
                    <a href="/categories?nameSort=AlphabeticallyReversed"><svg xmlns="http://www.w3.org/2000/svg" class="w-3 h-3 ml-1" aria-hidden="true" fill="currentColor" viewBox="0 0 320 512"><path d="M27.66 224h264.7c24.6 0 36.89-29.78 19.54-47.12l-132.3-136.8c-5.406-5.406-12.47-8.107-19.53-8.107c-7.055 0-14.09 2.701-19.45 8.107L8.119 176.9C-9.229 194.2 3.055 224 27.66 224zM292.3 288H27.66c-24.6 0-36.89 29.77-19.54 47.12l132.5 136.8C145.9 477.3 152.1 480 160 480c7.053 0 14.12-2.703 19.53-8.109l132.3-136.8C329.2 317.8 316.9 288 292.3 288z"/></svg></a>
                  <% end %>
                <% end %>
              </div>
            </th>
            <th scope="col" class="px-6 py-3">
              Description
            </th>
            <th scope="col" class="px-6 py-3">
            </th>
          </tr>
          </thead>
          <tbody>

            <%= render @categories %>

          </tbody>
        </table>
      </div>

    </div>

    <div class="my-5 text-center z-10 px-3 py-2 leading-tight dark:border-gray-700">
      <%= paginate @categories %>
    </div>

  <% end %>

</div>

<script type="text/javascript">
    paginators = document.getElementsByClassName('page current')
    paginators[0].style.color = "blue"; paginators[0].style.fontSize = "115%";
    paginators[1].style.color = "blue"; paginators[1].style.fontSize = "115%";
</script>

<!--Search hint by title jQuery-ui-->
<!--Not awesome but works-->
<script type="text/javascript">
    $(function() {
        $( "#search_categories_by_name" ).autocomplete({
            source: [ <% @array_of_category_names.length.times do |t| %>"<%= @array_of_category_names.at(t) %>", <% end %>],
        })
    })
</script>

app/views/categories/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New category</h1>

  <%= render "form", category: @category %>

  <%= link_to 'Back to categories', categories_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-300 inline-block font-medium" %>
</div>

app/views/categories/show.html.erb
<div class="mx-auto">
  <h1 class="font-bold text-4xl text-center">Category: <%= @category.id %></h1>
  <div class="flex justify-end">
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-8 h-8">
      <a xlink:href="<%= "/categories/#{@category.id}/edit" %>">
        <path d="M21.731 2.269a2.625 2.625 0 00-3.712 0l-1.157 1.157 3.712 3.712 1.157-1.157a2.625 2.625 0 000-3.712zM19.513 8.199l-3.712-3.712-8.4 8.4a5.25 5.25 0 00-1.32 2.214l-.8 2.685a.75.75 0 00.933.933l2.685-.8a5.25 5.25 0 002.214-1.32l8.4-8.4z" />
        <path d="M5.25 5.25a3 3 0 00-3 3v10.5a3 3 0 003 3h10.5a3 3 0 003-3V13.5a.75.75 0 00-1.5 0v5.25a1.5 1.5 0 01-1.5 1.5H5.25a1.5 1.5 0 01-1.5-1.5V8.25a1.5 1.5 0 011.5-1.5h5.25a.75.75 0 000-1.5H5.25z" />
      </a>
    </svg>
  </div>

  <div class="inline-block ml-2 flex justify-end">
    <%= button_to 'Delete', category_path(@category), method: :delete, class: "mt-2 rounded-lg py-1 px-2 bg-red-600 text-white font-medium", data: { turbo_confirm: 'Are you sure you want to delete this category? If you delete then all operations that belong to this CATEGORY also will be DELETED!' } %>
  </div>

  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div id="operations">

    <p class="my-5">
      <strong class="block font-medium mb-1">Name:</strong>
      <%= @category.name %>
    </p>

    <p class="my-5" style="word-wrap: break-word;">
      <strong class="block font-medium mb-1">Description:</strong>
      <%= @category.description %>
    </p>

  </div>

  <%= link_to "Back to categories", categories_path, class: "rounded-lg py-3 px-5 bg-gray-300 inline-block font-medium" %>
</div>