config/routes.rb
Rails.application.routes.draw do
  root 'main#index'

  get '/reports', to: 'reports#index'
  get '/reports/report_by_category', to: 'reports#report_by_category'
  get '/reports/report_by_dates', to: 'reports#report_by_dates'

  resources :operations
  resources :categories
end

app/models/operation.rb
class Operation < ApplicationRecord
  belongs_to :category

  validates :amount, :odate, :description, presence: true # validates_presence_of :amount, :odate, :description

  validates :amount, numericality: { greater_than: 0 }

  # Paginator [https://github.com/kaminari/kaminari]
  paginates_per 30 # default

  # search for operations for category name
  # LOWER(name) now working with SQLite when it is ukrainian / rus alphabet cause SQLite not using Unicode. But psql uses Unicode
  scope :search_by_category_name_scope, ->(name) { Operation.where(category_id: Category.where('LOWER(name) LIKE ?', "%#{name.gsub('+', ' ').downcase}%").ids) }

  private

  # report by category for a certain period of time
  # start_date = '2019-01-01' & end_date = '2020-01-01'
  def self.report_by_category_method(start_date, end_date)

    Operation.joins(:category).where('odate BETWEEN ? AND ?', start_date.to_s, end_date.to_s).group(:name).sum(:amount)

    # Others realizations of this method

    ## this case is not suitable because it returns ids instead of category names
    # Operation
    #  .where('odate BETWEEN ? AND ?', "#{start_date}", "#{end_date}")
    #    .group('category_id')
    #      .sum(:amount)

    ## using just WHERE
    # sql1 = "SELECT SUM(operations.amount) 'sum_amount', categories.name
    #      FROM operations, categories
    #      WHERE (operations.odate BETWEEN '#{start_date}' AND '#{end_date}') AND
    #      operations.category_id == categories.id
    #      GROUP BY categories.name"

    ## using INNER JOIN instead of just WHERE
    # sql2 = "SELECT SUM(operations.amount) 'sum', categories.name
    #       FROM operations
    #       INNER JOIN categories
    #         ON operations.category_id == categories.id
    #       WHERE operations.odate BETWEEN '#{start_date}' AND '#{start_date}'
    #       GROUP BY categories.name"

    ## ActiveRecord::Base.connection.execute(sql) - Command to run sql1 or sql2
  end

  # report by dates for a certain period of time
  # for example start_date = '2019-01-01' & end_date = '2019-01-06'
  def self.report_by_dates_method(start_date, end_date, datesReportType = 'perDay')

    operationsByDates = Operation.where('odate BETWEEN ? AND ?', start_date.to_s, end_date.to_s).order(:odate)

    resultHashByDates = Hash.new

    operationsByDates.each do |operation|

      if datesReportType == 'perDay'
        # per day
        odateString = operation.odate.to_date.to_s
      else
        # per month
        odateString = operation.odate.to_date.strftime("%B %Y") # return only month and year
      end

      if resultHashByDates[odateString].nil?
        resultHashByDates[odateString] = operation.amount
      else
        resultHashByDates[odateString] = resultHashByDates[odateString] + operation.amount
      end
    end

    return resultHashByDates
  end
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  before_action :set_operation, only: %i[ show edit update destroy ]

  # GET /operations or /operations.json
  def index
    @pageTitle = 'Your operations'

    # array of category names for jQuery search field
    @array_of_category_names = Category.pluck(:name)

    idSort = params[:idSort]
    amountSort = params[:amountSort]
    odateSort = params[:odateSort]
    operationsByCategorySort = params[:operationsByCategorySort]

    filter_options = params[:filter_operations_by_category_name]

    if filter_options != '' && !filter_options.nil?
      return @operations = Operation.search_by_category_name_scope(filter_options).page(params[:page])
    end

    # 1 by ID
    case idSort
    when 'Ascending'
      return @operations = Operation.all.order(:id).page(params[:page])
    when 'Descending'
      return @operations = Operation.all.order(id: :desc).page(params[:page])
    end

    # 2 by Amount
    case amountSort
    when 'Ascending'
      return @operations = Operation.all.order(:amount).page(params[:page])
    when 'Descending'
      return @operations = Operation.all.order(amount: :desc).page(params[:page])
    end

    # 3 by OperationDate
    case odateSort
    when 'Ascending'
      return @operations = Operation.all.order(:odate).page(params[:page])
    when 'Descending'
      return @operations = Operation.all.order(odate: :desc).page(params[:page])
    end

    # 4 by Categories
    case operationsByCategorySort
    when 'Alphabetically'
      return @operations = Operation.all.order(:category_id).page(params[:page])
    when 'AlphabeticallyReversed'
      return @operations = Operation.all.order(category_id: :desc).page(params[:page])
    end

    @operations = Operation.all.order(odate: :desc).page(params[:page])
  end

  # GET /operations/1 or /operations/1.json
  def show
    @pageTitle = "Operation #{@operation.id}"
  end

  # GET /operations/new
  def new
    @pageTitle = 'New operation'

    @operation = Operation.new
  end

  # GET /operations/1/edit
  def edit
    @pageTitle = "Edit operation #{@operation.id}"
  end

  # POST /operations or /operations.json
  def create
    @operation = Operation.new(operation_params)

    respond_to do |format|
      if @operation.save
        format.html { redirect_to operation_url(@operation), notice: "Operation was successfully created." }
        format.json { render :show, status: :created, location: @operation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /operations/1 or /operations/1.json
  def update
    respond_to do |format|
      if @operation.update(operation_params)
        format.html { redirect_to operation_url(@operation), notice: "Operation was successfully updated." }
        format.json { render :show, status: :ok, location: @operation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /operations/1 or /operations/1.json
  def destroy
    @operation.destroy

    respond_to do |format|
      format.html { redirect_to operations_url, notice: "Operation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_operation
      @operation = Operation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def operation_params
      params.require(:operation).permit(:otype, :amount, :odate, :description, :category_id)
    end
end

app/helpers/operations_helper.rb
module OperationsHelper
end

app/views/operations/_form.html.erb
<!--
  Slimselect
  <script src="https://unpkg.com/slim-select@latest/dist/slimselect.min.js"></script>
  <link href="https://unpkg.com/slim-select@latest/dist/slimselect.css" rel="stylesheet"></link>
-->

<%= stylesheet_link_tag 'slimselect_folder/slimselect.css' %>
<%= javascript_include_tag 'slimselect_folder/slimselect.min.js' %>

<%= form_with(model: operation, class: "contents") do |form| %>
  <% if operation.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(operation.errors.count, "error") %> prohibited this operation from being saved:</h2>

      <ul>
        <% operation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :amount %>
    <%= form.text_field :amount, required: true, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    <p class="text-sm font-light">max 99 999 999.99</p>
  </div>

  <div class="my-5">
    <%= form.label :odate %>
    <%= form.datetime_field :odate, required: true, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_field :description, required: true, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :category_id %>
    <%= form.select :category_id, Category.pluck(:name, :id), {}, { id: 'selectCategory', class: 'text-lg', required: true } %>
  </div>

  <div class="inline m-2">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

<script type="text/javascript">
    $(document).ready(function() {
      new SlimSelect({
          select: '#selectCategory'
      })
    });
</script>

app/views/operations/_operation.html.erb
<div id="<%= dom_id operation %>">

  <tr class="bg-white border-b dark:bg-gray-900 dark:border-gray-700">
    <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
      <%= operation.id %>
    </th>
    <td class="px-6 py-4">
      <%= link_to operation.amount, operation, class: "text-lg text-blue-500" %>
    </td>
    <td class="px-6 py-4">
      <%= operation.odate %>
    </td>
    <td class="px-6 py-4">
      <%= Category.find(operation.category_id).name %>
    </td>
    <td class="px-6 py-4">
      <% if action_name != "show" %>
        <div class="flex justify-end">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-8 h-8">
            <a xlink:href="<%= "/operations/#{operation.id}/edit" %>">
              <path d="M21.731 2.269a2.625 2.625 0 00-3.712 0l-1.157 1.157 3.712 3.712 1.157-1.157a2.625 2.625 0 000-3.712zM19.513 8.199l-3.712-3.712-8.4 8.4a5.25 5.25 0 00-1.32 2.214l-.8 2.685a.75.75 0 00.933.933l2.685-.8a5.25 5.25 0 002.214-1.32l8.4-8.4z" />
              <path d="M5.25 5.25a3 3 0 00-3 3v10.5a3 3 0 003 3h10.5a3 3 0 003-3V13.5a.75.75 0 00-1.5 0v5.25a1.5 1.5 0 01-1.5 1.5H5.25a1.5 1.5 0 01-1.5-1.5V8.25a1.5 1.5 0 011.5-1.5h5.25a.75.75 0 000-1.5H5.25z" />
            </a>
          </svg>
        </div>
      <% end %>
    </td>
  </tr>

</div>

app/views/operations/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing operation</h1>

  <%= render "form", operation: @operation %>

  <%= link_to "Show this operation", @operation, class: "rounded-lg py-3 px-5 bg-gray-300 inline-block font-medium m-2" %>
  <%= link_to "Back to operations", operations_path, class: "rounded-lg py-3 px-5 bg-gray-300 inline-block font-medium m-2" %>
</div>

app/views/operations/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl my-5">Operations</h1>
    <%= link_to 'New operation', new_operation_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <%= form_tag "/operations", method: :get do %>
    <div class="flex items-center">
      <%= text_field_tag(:filter_operations_by_category_name, params[:filter_operations_by_category_name], id: "filter_operations_by_category_name_field", class: "w-full block h-12 z-20 text-sm text-gray-900 bg-gray-50 border-gray-300", placeholder: "Category name...") %>
      <%= submit_tag "Search", class: "rounded-r-lg p-3 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
    </div>
    <a class="p-1 bg-red-600 text-white px-3 inline-block text-sm cursor-pointer rounded-b-lg" href="/operations">Reset</a>
    <b><%= @operations.total_count %></b> record(s)
  <% end %>

  <% if @operations.total_count != 0 %>

    <div class="my-2 text-center z-10 px-3 py-2 leading-tight dark:border-gray-700">
      <%= paginate @operations %>
    </div>

    <div id="operations" class="min-w-full">

      <div class="relative overflow-x-auto shadow-md sm:rounded-lg mb-5">
        <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
          <thead class="text-xs text-gray-700 uppercase bg-gray-300 dark:bg-gray-700 dark:text-gray-400">
          <tr>
            <th scope="col" class="px-6 py-3">
              <div class="flex items-center">
                ID

                <!--Sort Operations by id Ascending or Descending-->
                <% if request[:idSort] != 'Ascending' && request[:idSort] != 'Descending' %>
                  <a href="/operations?idSort=Descending"><svg xmlns="http://www.w3.org/2000/svg" class="w-3 h-3 ml-1" aria-hidden="true" fill="currentColor" viewBox="0 0 320 512"><path d="M27.66 224h264.7c24.6 0 36.89-29.78 19.54-47.12l-132.3-136.8c-5.406-5.406-12.47-8.107-19.53-8.107c-7.055 0-14.09 2.701-19.45 8.107L8.119 176.9C-9.229 194.2 3.055 224 27.66 224zM292.3 288H27.66c-24.6 0-36.89 29.77-19.54 47.12l132.5 136.8C145.9 477.3 152.1 480 160 480c7.053 0 14.12-2.703 19.53-8.109l132.3-136.8C329.2 317.8 316.9 288 292.3 288z"/></svg></a>
                <% else %>
                  <% if request[:idSort] == 'Descending' %>
                    <a href="/operations?idSort=Ascending"><svg xmlns="http://www.w3.org/2000/svg" class="w-3 h-3 ml-1" aria-hidden="true" fill="currentColor" viewBox="0 0 320 512"><path d="M27.66 224h264.7c24.6 0 36.89-29.78 19.54-47.12l-132.3-136.8c-5.406-5.406-12.47-8.107-19.53-8.107c-7.055 0-14.09 2.701-19.45 8.107L8.119 176.9C-9.229 194.2 3.055 224 27.66 224zM292.3 288H27.66c-24.6 0-36.89 29.77-19.54 47.12l132.5 136.8C145.9 477.3 152.1 480 160 480c7.053 0 14.12-2.703 19.53-8.109l132.3-136.8C329.2 317.8 316.9 288 292.3 288z"/></svg></a>
                  <% else %>
                    <a href="/operations?idSort=Descending"><svg xmlns="http://www.w3.org/2000/svg" class="w-3 h-3 ml-1" aria-hidden="true" fill="currentColor" viewBox="0 0 320 512"><path d="M27.66 224h264.7c24.6 0 36.89-29.78 19.54-47.12l-132.3-136.8c-5.406-5.406-12.47-8.107-19.53-8.107c-7.055 0-14.09 2.701-19.45 8.107L8.119 176.9C-9.229 194.2 3.055 224 27.66 224zM292.3 288H27.66c-24.6 0-36.89 29.77-19.54 47.12l132.5 136.8C145.9 477.3 152.1 480 160 480c7.053 0 14.12-2.703 19.53-8.109l132.3-136.8C329.2 317.8 316.9 288 292.3 288z"/></svg></a>
                  <% end %>
                <% end %>
              </div>
            </th>
            <th scope="col" class="px-6 py-3">
              <div class="flex items-center">
                Amount

                <!--Sort Operations by amount Ascending or Descending-->
                <% if request[:amountSort] != 'Ascending' && request[:amountSort] != 'Descending' %>
                  <a href="/operations?amountSort=Descending"><svg xmlns="http://www.w3.org/2000/svg" class="w-3 h-3 ml-1" aria-hidden="true" fill="currentColor" viewBox="0 0 320 512"><path d="M27.66 224h264.7c24.6 0 36.89-29.78 19.54-47.12l-132.3-136.8c-5.406-5.406-12.47-8.107-19.53-8.107c-7.055 0-14.09 2.701-19.45 8.107L8.119 176.9C-9.229 194.2 3.055 224 27.66 224zM292.3 288H27.66c-24.6 0-36.89 29.77-19.54 47.12l132.5 136.8C145.9 477.3 152.1 480 160 480c7.053 0 14.12-2.703 19.53-8.109l132.3-136.8C329.2 317.8 316.9 288 292.3 288z"/></svg></a>
                <% else %>
                  <% if request[:amountSort] == 'Descending' %>
                    <a href="/operations?amountSort=Ascending"><svg xmlns="http://www.w3.org/2000/svg" class="w-3 h-3 ml-1" aria-hidden="true" fill="currentColor" viewBox="0 0 320 512"><path d="M27.66 224h264.7c24.6 0 36.89-29.78 19.54-47.12l-132.3-136.8c-5.406-5.406-12.47-8.107-19.53-8.107c-7.055 0-14.09 2.701-19.45 8.107L8.119 176.9C-9.229 194.2 3.055 224 27.66 224zM292.3 288H27.66c-24.6 0-36.89 29.77-19.54 47.12l132.5 136.8C145.9 477.3 152.1 480 160 480c7.053 0 14.12-2.703 19.53-8.109l132.3-136.8C329.2 317.8 316.9 288 292.3 288z"/></svg></a>
                  <% else %>
                    <a href="/operations?amountSort=Descending"><svg xmlns="http://www.w3.org/2000/svg" class="w-3 h-3 ml-1" aria-hidden="true" fill="currentColor" viewBox="0 0 320 512"><path d="M27.66 224h264.7c24.6 0 36.89-29.78 19.54-47.12l-132.3-136.8c-5.406-5.406-12.47-8.107-19.53-8.107c-7.055 0-14.09 2.701-19.45 8.107L8.119 176.9C-9.229 194.2 3.055 224 27.66 224zM292.3 288H27.66c-24.6 0-36.89 29.77-19.54 47.12l132.5 136.8C145.9 477.3 152.1 480 160 480c7.053 0 14.12-2.703 19.53-8.109l132.3-136.8C329.2 317.8 316.9 288 292.3 288z"/></svg></a>
                  <% end %>
                <% end %>
              </div>
            </th>
            <th scope="col" class="px-6 py-3">
              <div class="flex items-center">
                Odate

                <!--Sort Operations by id Ascending or Descending-->
                <% if request[:odateSort] != 'Ascending' && request[:odateSort] != 'Descending' %>
                  <a href="/operations?odateSort=Descending"><svg xmlns="http://www.w3.org/2000/svg" class="w-3 h-3 ml-1" aria-hidden="true" fill="currentColor" viewBox="0 0 320 512"><path d="M27.66 224h264.7c24.6 0 36.89-29.78 19.54-47.12l-132.3-136.8c-5.406-5.406-12.47-8.107-19.53-8.107c-7.055 0-14.09 2.701-19.45 8.107L8.119 176.9C-9.229 194.2 3.055 224 27.66 224zM292.3 288H27.66c-24.6 0-36.89 29.77-19.54 47.12l132.5 136.8C145.9 477.3 152.1 480 160 480c7.053 0 14.12-2.703 19.53-8.109l132.3-136.8C329.2 317.8 316.9 288 292.3 288z"/></svg></a>
                <% else %>
                  <% if request[:odateSort] == 'Descending' %>
                    <a href="/operations?odateSort=Ascending"><svg xmlns="http://www.w3.org/2000/svg" class="w-3 h-3 ml-1" aria-hidden="true" fill="currentColor" viewBox="0 0 320 512"><path d="M27.66 224h264.7c24.6 0 36.89-29.78 19.54-47.12l-132.3-136.8c-5.406-5.406-12.47-8.107-19.53-8.107c-7.055 0-14.09 2.701-19.45 8.107L8.119 176.9C-9.229 194.2 3.055 224 27.66 224zM292.3 288H27.66c-24.6 0-36.89 29.77-19.54 47.12l132.5 136.8C145.9 477.3 152.1 480 160 480c7.053 0 14.12-2.703 19.53-8.109l132.3-136.8C329.2 317.8 316.9 288 292.3 288z"/></svg></a>
                  <% else %>
                    <a href="/operations?odateSort=Descending"><svg xmlns="http://www.w3.org/2000/svg" class="w-3 h-3 ml-1" aria-hidden="true" fill="currentColor" viewBox="0 0 320 512"><path d="M27.66 224h264.7c24.6 0 36.89-29.78 19.54-47.12l-132.3-136.8c-5.406-5.406-12.47-8.107-19.53-8.107c-7.055 0-14.09 2.701-19.45 8.107L8.119 176.9C-9.229 194.2 3.055 224 27.66 224zM292.3 288H27.66c-24.6 0-36.89 29.77-19.54 47.12l132.5 136.8C145.9 477.3 152.1 480 160 480c7.053 0 14.12-2.703 19.53-8.109l132.3-136.8C329.2 317.8 316.9 288 292.3 288z"/></svg></a>
                  <% end %>
                <% end %>
              </div>
            </th>
            <th scope="col" class="px-6 py-3">
              <div class="flex items-center">
                Category

                <!--Sort Operations by id Ascending or Descending-->
                <% if request[:operationsByCategorySort] != 'AlphabeticallyReversed' && request[:operationsByCategorySort] != 'Alphabetically' %>
                  <a href="/operations?operationsByCategorySort=AlphabeticallyReversed"><svg xmlns="http://www.w3.org/2000/svg" class="w-3 h-3 ml-1" aria-hidden="true" fill="currentColor" viewBox="0 0 320 512"><path d="M27.66 224h264.7c24.6 0 36.89-29.78 19.54-47.12l-132.3-136.8c-5.406-5.406-12.47-8.107-19.53-8.107c-7.055 0-14.09 2.701-19.45 8.107L8.119 176.9C-9.229 194.2 3.055 224 27.66 224zM292.3 288H27.66c-24.6 0-36.89 29.77-19.54 47.12l132.5 136.8C145.9 477.3 152.1 480 160 480c7.053 0 14.12-2.703 19.53-8.109l132.3-136.8C329.2 317.8 316.9 288 292.3 288z"/></svg></a>
                <% else %>
                  <% if request[:operationsByCategorySort] == 'AlphabeticallyReversed' %>
                    <a href="/operations?operationsByCategorySort=Alphabetically"><svg xmlns="http://www.w3.org/2000/svg" class="w-3 h-3 ml-1" aria-hidden="true" fill="currentColor" viewBox="0 0 320 512"><path d="M27.66 224h264.7c24.6 0 36.89-29.78 19.54-47.12l-132.3-136.8c-5.406-5.406-12.47-8.107-19.53-8.107c-7.055 0-14.09 2.701-19.45 8.107L8.119 176.9C-9.229 194.2 3.055 224 27.66 224zM292.3 288H27.66c-24.6 0-36.89 29.77-19.54 47.12l132.5 136.8C145.9 477.3 152.1 480 160 480c7.053 0 14.12-2.703 19.53-8.109l132.3-136.8C329.2 317.8 316.9 288 292.3 288z"/></svg></a>
                  <% else %>
                    <a href="/operations?operationsByCategorySort=AlphabeticallyReversed"><svg xmlns="http://www.w3.org/2000/svg" class="w-3 h-3 ml-1" aria-hidden="true" fill="currentColor" viewBox="0 0 320 512"><path d="M27.66 224h264.7c24.6 0 36.89-29.78 19.54-47.12l-132.3-136.8c-5.406-5.406-12.47-8.107-19.53-8.107c-7.055 0-14.09 2.701-19.45 8.107L8.119 176.9C-9.229 194.2 3.055 224 27.66 224zM292.3 288H27.66c-24.6 0-36.89 29.77-19.54 47.12l132.5 136.8C145.9 477.3 152.1 480 160 480c7.053 0 14.12-2.703 19.53-8.109l132.3-136.8C329.2 317.8 316.9 288 292.3 288z"/></svg></a>
                  <% end %>
                <% end %>
              </div>
            </th>
            <th scope="col" class="px-6 py-3">
            </th>
          </tr>
          </thead>
          <tbody>

            <%= render @operations %>

          </tbody>
        </table>
      </div>

    </div>

    <div class="my-2 text-center z-10 px-3 py-2 leading-tight dark:border-gray-700">
      <%= paginate @operations %>
    </div>

  <% end %>

</div>

<script type="text/javascript">
    paginators = document.getElementsByClassName('page current')
    paginators[0].style.color = "blue"; paginators[0].style.fontSize = "115%";
    paginators[1].style.color = "blue"; paginators[1].style.fontSize = "115%";
</script>

<!--Search hint by title jQuery-ui-->
<!--Not awesome but works-->
<script type="text/javascript">
    $(function() {
        $( "#filter_operations_by_category_name_field" ).autocomplete({
            source: [ <% @array_of_category_names.length.times do |t| %>"<%= @array_of_category_names.at(t) %>", <% end %>],
        })
    })
</script>

<script src="https://unpkg.com/slim-select@latest/dist/slimselect.min.js"></script>
<link href="https://unpkg.com/slim-select@latest/dist/slimselect.css" rel="stylesheet"></link>

<script type="text/javascript">
    new SlimSelect({
        select: '#filter_operations_by_category_name_field'
    })
</script>

app/views/operations/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New operation</h1>

  <%= render "form", operation: @operation %>

  <%= link_to 'Back to operations', operations_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-300 inline-block font-medium" %>
</div>

app/views/operations/show.html.erb
<div class="mx-auto">

  <h1 class="font-bold text-4xl text-center">Operation: <%= @operation.id %></h1>
  <div class="flex justify-end">
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-8 h-8">
      <a xlink:href="<%= "/operations/#{@operation.id}/edit" %>">
        <path d="M21.731 2.269a2.625 2.625 0 00-3.712 0l-1.157 1.157 3.712 3.712 1.157-1.157a2.625 2.625 0 000-3.712zM19.513 8.199l-3.712-3.712-8.4 8.4a5.25 5.25 0 00-1.32 2.214l-.8 2.685a.75.75 0 00.933.933l2.685-.8a5.25 5.25 0 002.214-1.32l8.4-8.4z" />
        <path d="M5.25 5.25a3 3 0 00-3 3v10.5a3 3 0 003 3h10.5a3 3 0 003-3V13.5a.75.75 0 00-1.5 0v5.25a1.5 1.5 0 01-1.5 1.5H5.25a1.5 1.5 0 01-1.5-1.5V8.25a1.5 1.5 0 011.5-1.5h5.25a.75.75 0 000-1.5H5.25z" />
      </a>
    </svg>
  </div>

  <div class="inline-block ml-2 flex justify-end">
    <%= button_to 'Delete', operation_path(@operation), method: :delete, class: "mt-2 rounded-lg py-1 text-white px-2 bg-red-600 font-medium", data: { turbo_confirm: 'Are you sure you want to delete this operation?' } %>
  </div>

  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>


  <div id="operations">

    <p class="my-5">
      <strong class="block font-medium mb-1">Amount:</strong>
      <b><%= @operation.amount %></b>
    </p>

    <p class="my-5">
      <strong class="block font-medium mb-1">Operation date:</strong>
      <%= @operation.odate %>
    </p>

    <p class="my-5">
      <strong class="block font-medium mb-1">Category:</strong>
      <%= Category.find(@operation.category_id).name %>
    </p>

    <p class="my-5" style="word-wrap: break-word;">
      <strong class="block font-medium mb-1">Description:</strong>
      <%= @operation.description %>
    </p>

  </div>

  <%= link_to 'Back to operations', operations_path, class: "ml-2 mt-2 rounded-lg py-3 px-5 bg-gray-300 inline-block font-medium" %>
</div>